# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

## Lista de Estado da Cadastrados
Estado.create(:id => 1, :nome => 'Distrito Federal', :sigla => 'DF')
Estado.create(:id => 2, :nome => 'Goiás', :sigla => 'GO')

## Lista de Municípios Cadastrados
Municipio.create(:id => 1, :nome => 'BRASILIA', :estado_id => 1)
Municipio.create(:id => 2, :nome => 'OCIDENTAL', :estado_id => 2)
Municipio.create(:id => 3, :nome => 'ÁGUAS LINDAS', :estado_id => 2)

## Lista de Cidades Cadastradas
Cidade.create(:id => 1, :nome => 'SANTA MARIA', :municipio_id => 1)
Cidade.create(:id => 2, :nome => 'GAMA', :municipio_id => 1)
Cidade.create(:id => 3, :nome => 'SAMAMBAIA', :municipio_id => 1)
Cidade.create(:id => 4, :nome => 'RECANTO DAS EMAS', :municipio_id => 1)
Cidade.create(:id => 5, :nome => 'SÃO SEBASTIÃO', :municipio_id => 1)
Cidade.create(:id => 6, :nome => 'VALPARAISO', :municipio_id => 1)
Cidade.create(:id => 7, :nome => 'NOVO GAMA', :municipio_id => 1)
Cidade.create(:id => 8, :nome => 'ÁGUAS LINDAS', :municipio_id => 1)
Cidade.create(:id => 9, :nome => 'OCIDENTAL', :municipio_id => 1)
Cidade.create(:id => 10, :nome => 'VARJÃO', :municipio_id => 1)
Cidade.create(:id => 11, :nome => 'TAGUATINGA', :municipio_id => 1)
Cidade.create(:id => 12, :nome => 'RIACHO FUNDO I', :municipio_id => 1)
Cidade.create(:id => 13, :nome => 'RIACHO FUNDO II', :municipio_id => 1)
Cidade.create(:id => 14, :nome => 'LAGO AZUL', :municipio_id => 1)
Cidade.create(:id => 16, :nome => 'VICENTE PIRES', :municipio_id => 1)
Cidade.create(:id => 17, :nome => 'ÁGUAS CLARAS', :municipio_id => 1)
Cidade.create(:id => 18, :nome => 'ARNIQUEIRA', :municipio_id => 1)
Cidade.create(:id => 21, :nome => 'Sem CIDADE', :municipio_id => 1)
Cidade.create(:id => 23, :nome => 'D.V.O', :municipio_id => 1)
Cidade.create(:id => 24, :nome => 'CEILÂNDIA', :municipio_id => 1)
Cidade.create(:id => 25, :nome => 'MARINHA', :municipio_id => 1)
Cidade.create(:id => 26, :nome => 'BRASLÂNDIA', :municipio_id => 1)
Cidade.create(:id => 27, :nome => 'GUARÁ', :municipio_id => 1)
Cidade.create(:id => 30, :nome => 'VALPARAISO', :municipio_id => 1)

## Lista de Bairros Cadastrados

Bairro.create(:id => 1, :nome => 'SANTA MARIA NORTE ', :cidade_id => '1')
Bairro.create(:id => 2, :nome => 'SANTA MARIA SUL', :cidade_id => '1')
Bairro.create(:id => 3, :nome => 'SETOR NORTE', :cidade_id => '2')
Bairro.create(:id => 4, :nome => 'SETOR SUL', :cidade_id => '2')
Bairro.create(:id => 5, :nome => 'SETOR OESTE', :cidade_id => '2')
Bairro.create(:id => 6, :nome => 'SETOR LESTE', :cidade_id => '2')
Bairro.create(:id => 7, :nome => 'SETOR CENTRAL', :cidade_id => '2')
Bairro.create(:id => 8, :nome => 'TAGUATINGA NORTE', :cidade_id => '11')
Bairro.create(:id => 9, :nome => 'TAGUATINGA SUL', :cidade_id => '11')
Bairro.create(:id => 10, :nome => 'SANTA MARIA CENTRAL', :cidade_id => '1')
Bairro.create(:id => 11, :nome => 'JARDIM ABC', :cidade_id => '9')
Bairro.create(:id => 12, :nome => 'Sem BAIRRO', :cidade_id => '21')
Bairro.create(:id => 13, :nome => 'SETOR DE INDUSTRIA', :cidade_id => '2')
Bairro.create(:id => 14, :nome => 'PORTO RICO', :cidade_id => '1')
Bairro.create(:id => 15, :nome => 'D.V.O', :cidade_id => '2')
Bairro.create(:id => 16, :nome => 'UNABEL', :cidade_id => '14')
Bairro.create(:id => 17, :nome => 'NOVO GAMA', :cidade_id => '7')
Bairro.create(:id => 18, :nome => 'SANTOS DUMONT', :cidade_id => '1')
Bairro.create(:id => 19, :nome => 'BOA VISTA', :cidade_id => '23')
Bairro.create(:id => 20, :nome => 'CEILANDIA NORTE', :cidade_id => '24')
Bairro.create(:id => 21, :nome => 'CEILANDIA SUL ', :cidade_id => '24')
Bairro.create(:id => 22, :nome => 'PEDREGAL', :cidade_id => '7')
Bairro.create(:id => 23, :nome => 'SAMAMBAIA SUL', :cidade_id => '3')
Bairro.create(:id => 24, :nome => 'LAGO NORTE', :cidade_id => '26')
Bairro.create(:id => 25, :nome => 'GUARÁ I', :cidade_id => '27')
Bairro.create(:id => 26, :nome => 'GUARÁ II', :cidade_id => '27')
Bairro.create(:id => 27, :nome => 'LAGO SUL', :cidade_id => '26')
Bairro.create(:id => 28, :nome => 'SÃO SEBASTIÃO', :cidade_id => '26')
Bairro.create(:id => 29, :nome => 'CRUZEIRO', :cidade_id => '26')
Bairro.create(:id => 30, :nome => 'BRAZLÂNDIA', :cidade_id => '26')
Bairro.create(:id => 31, :nome => 'ARNIQUEIRAS', :cidade_id => '18')
Bairro.create(:id => 32, :nome => 'P NORTE', :cidade_id => '24')
Bairro.create(:id => 33, :nome => 'MORADA NOBRE', :cidade_id => '26')
Bairro.create(:id => 34, :nome => 'CEU AZUL', :cidade_id => '7')
Bairro.create(:id => 35, :nome => 'RECANTO DAS EMAS', :cidade_id => '26')
Bairro.create(:id => 36, :nome => 'JARDIM INGA', :cidade_id => '6')
